In [195]:
import pandas as pd

In [196]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [197]:
train_data.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [198]:
train_data.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [199]:
train_data.shape

(4209, 378)

In [200]:
train_data.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [201]:
test_data.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [202]:
test_data.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Both test and train dataset doesnot contains null vlaues

In [203]:
(train_data.var().values == 0)

/tmp/ipykernel_124/166771571.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  (train_data.var().values == 0)


array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [204]:
row_zero_variance = train_data.var()[(train_data.var() == 0)].index.values
row_zero_variance

/tmp/ipykernel_124/3853754429.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  row_zero_variance = train_data.var()[(train_data.var() == 0)].index.values


array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [205]:
train_data = train_data.drop(row_zero_variance,axis = 1)

In [206]:
train_data

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [207]:
train_data.shape

(4209, 366)

In [208]:
train_data.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [209]:
test_data.var().values

/tmp/ipykernel_124/2201900978.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  test_data.var().values


array([5.87131148e+06, 1.86500591e-02, 2.37586125e-04, 6.88507426e-02,
       5.73449796e-02, 2.44858699e-01, 7.12419611e-04, 2.60723671e-03,
       8.71548113e-03, 1.01142356e-02, 9.92198729e-02, 1.20041632e-01,
       1.66073153e-03, 7.56636151e-02, 1.97916921e-02, 2.37077980e-03,
       8.94888917e-03, 2.17232876e-01, 2.61326670e-02, 3.74548202e-02,
       5.43591182e-03, 1.81057227e-01, 1.03469661e-02, 7.12419611e-04,
       3.55193515e-03, 1.81057227e-01, 2.84358070e-03, 1.81057227e-01,
       3.01622587e-02, 7.12419611e-04, 1.89752721e-03, 1.12767589e-02,
       1.42382293e-03, 7.10691918e-02, 6.84415163e-03, 1.88579922e-01,
       2.41272436e-01, 1.10444801e-02, 2.31996527e-02, 1.15722397e-01,
       1.73889443e-01, 2.03969947e-01, 4.07289693e-02, 5.90577678e-03,
       3.83304109e-02, 6.37519005e-03, 2.43299936e-02, 1.54384684e-02,
       2.42923908e-01, 1.18680141e-03, 1.66073153e-03, 4.44089571e-02,
       5.90577678e-03, 1.28995489e-02, 2.30505291e-01, 1.89752721e-03,
      

In [210]:
row_zero_variance_test = test_data.var()[test_data.var() == 0].index.values

/tmp/ipykernel_124/1161072003.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  row_zero_variance_test = test_data.var()[test_data.var() == 0].index.values


In [211]:
row_zero_variance_test

array(['X257', 'X258', 'X295', 'X296', 'X369'], dtype=object)

test_data.shape

In [212]:
test_data = test_data.drop(row_zero_variance_test, axis = 1)

In [213]:
test_data.shape

(4209, 372)

Data with zero variance are dropped from both train and test set

In [214]:
train_data_col = train_data.dtypes.reset_index()
train_data_col.columns = ["feature name","dtypes"]
train_data_col.groupby("dtypes").agg("count").reset_index()

dtypes  feature name
0    int64           357
1  float64             1
2   object             8

In [215]:
# Column heading with categorical variable

object_train_data = train_data.select_dtypes(include=[object])
object_train_data

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [216]:
# Analysis of categorical variable
import seaborn as sns

In [217]:
train_data.nunique()

ID      4209
y       2545
X0        47
X1        27
X2        44
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 366, dtype: int64

In [218]:
test_data.nunique()

ID      4209
X0        49
X1        27
X2        45
X3         7
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 372, dtype: int64

In [219]:
train_data = train_data.drop(["ID"], axis = 1)


In [220]:
train_data.shape

(4209, 365)

In [221]:
test_data = test_data.drop("ID",axis = 1)

In [222]:
test_data.shape

(4209, 371)

Dropped the unique ID from both train as test data set

In [223]:
# Initializing label Encoder

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder()


In [224]:
object_train_data.columns

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [225]:
train_data["X0"] = label_encoder.fit_transform(train_data["X0"])
train_data["X0"].unique()

array([32, 20, 40,  9, 36, 43, 31, 29, 39, 35, 19, 27, 44, 45,  7,  8, 10,
       46, 37, 15, 12, 42,  5,  0, 26,  6, 25, 13, 24,  1, 22, 14, 30, 38,
       21, 18, 23, 41,  4, 16, 34, 33, 17, 11,  3, 28,  2])

In [226]:
train_data["X1"] = label_encoder.fit_transform(train_data["X1"])
train_data["X2"] = label_encoder.fit_transform(train_data["X2"])
train_data["X3"] = label_encoder.fit_transform(train_data["X3"])
train_data["X4"] = label_encoder.fit_transform(train_data["X4"])
train_data["X5"] = label_encoder.fit_transform(train_data["X5"])
train_data["X6"] = label_encoder.fit_transform(train_data["X6"])
train_data["X8"] = label_encoder.fit_transform(train_data["X8"])

In [227]:
train_data.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  130.81  32  23  17   0   3  24   9  14    0  ...     0     0     1     0   
1   88.53  32  21  19   4   3  28  11  14    0  ...     1     0     0     0   
2   76.26  20  24  34   2   3  27   9  23    0  ...     0     0     0     0   
3   80.62  20  21  34   5   3  27  11   4    0  ...     0     0     0     0   
4   78.02  20  23  34   5   3  12   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 365 columns]

By applying label ecoder all the categorical values are converted into their numerical counterparts

In [228]:
# For dimensionality reduction using the pricipal component analysis
from sklearn.decomposition import PCA

In [229]:
# PCA with 95% quartile range
sklearn_pca = PCA(n_components=0.95)

In [230]:
sklearn_pca.fit(train_data)


PCA(n_components=0.95)

In [231]:
train_data_transformed = sklearn_pca.transform(train_data)

In [232]:
train_data_transformed.shape

(4209, 6)

In [233]:
# PCA with 98% quartile range
sklearn_pca_1 = PCA(n_components = 0.98)

In [234]:
sklearn_pca_1.fit(train_data)

PCA(n_components=0.98)

In [235]:
sklearn_pca_1_transform = sklearn_pca_1.transform(train_data)

In [236]:
sklearn_pca_1_transform.shape

(4209, 12)

In [237]:
# Splitting the train_data into train & test 
X = train_data.drop("y", axis = 1)
y = train_data.y


In [238]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size = 0.3, random_state=40)

In [239]:
xtrain.shape

(2946, 364)

In [240]:
ytrain.shape

(2946,)

In [241]:
xtest.shape

(1263, 364)

In [242]:
ytest.shape

(1263,)

In [243]:
# PCA with 95% on xtrain
pca_xtrain = PCA(n_components = 0.95)
pca_xtrain.fit(xtrain)

PCA(n_components=0.95)

In [246]:
pca_xtrain_transform = pca_xtrain.transform(xtrain)
pca_xtrain_transform.shape

(2946, 6)

In [248]:
# PCA with 95% with xtest
pca_xtest = PCA(n_components = 0.95)
pca_xtest.fit(xtest)

PCA(n_components=0.95)

In [250]:
pca_xtest_transform = pca_xtest.transform(xtest)
pca_xtest_transform.shape

(1263, 6)

In [253]:
print(pca_xtest.explained_variance_)

[203.9653055  115.57344966  69.24308582  65.86254724  49.77016743
   8.13612335]


In [258]:
print(pca_xtest.explained_variance_ratio_)

[0.38058568 0.21565236 0.12920299 0.12289513 0.09286782 0.01518146]


In [261]:
# PCA for test dataset
test_data.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   
3  az  l   n  f  d  z  l  n    0    0  ...     0     0     0     1     0   
4   w  s  as  c  d  y  i  m    0    0  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 371 columns]

In [269]:
# Identify the datahead containing categorical variable 
object_test_data = test_data.select_dtypes(include= [object])
object_test_data.shape

(4209, 8)

In [273]:
object_test_data.columns

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [276]:
test_data["X0"] = label_encoder.fit_transform(test_data["X0"])
test_data["X1"] = label_encoder.fit_transform(test_data["X1"])
test_data["X2"] = label_encoder.fit_transform(test_data["X2"])
test_data["X3"] = label_encoder.fit_transform(test_data["X3"])
test_data["X4"] = label_encoder.fit_transform(test_data["X4"])
test_data["X5"] = label_encoder.fit_transform(test_data["X5"])
test_data["X6"] = label_encoder.fit_transform(test_data["X6"])
test_data["X8"] = label_encoder.fit_transform(test_data["X8"])          

In [277]:
test_data.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 371 columns]

In [279]:
# PCA with 95% for test_data
pca_test_data = PCA(n_components = 0.95)
pca_test_data.fit(test_data)

PCA(n_components=0.95)

In [280]:
pca_test_data_transform= pca_test_data.transform(test_data)
pca_test_data_transform.shape

(4209, 6)

In [282]:
pca_test_data.explained_variance_

array([247.07875325, 100.33535335,  77.48364816,  62.33258307,
        48.95689653,   8.14203723])

In [284]:
y.shape

(4209,)

Dimensionality of data is reduced to 6 categorical variable from total 8 on the basis of PCA on both test and train data 

In [285]:
# Perform XGboost

from sklearn import svm
from sklearn import model_selection
import xgboost as xgb


In [322]:
model = xgb.XGBRegressor(objective = "reg:linear", learning_rate = 0.1)

In [323]:
model.fit(xtrain,ytrain)

[08:48:29] WARNING: ../src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=0, reg_alpha=0, ...)

In [324]:
y_prediction = model.predict(xtest)
y_prediction

array([114.27982 , 103.89707 ,  93.200966, ..., 112.40911 ,  93.57714 ,
       108.37921 ], dtype=float32)